ALTER TABLE feedback ADD COLUMN IF NOT EXISTS retry_count INT DEFAULT 0 NOT NULL;
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS raw_ai_response TEXT;
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS analysis_json JSONB;
